services:
  - type: web
    name: eureka-server
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_APPLICATION_NAME
        value: eureka-server
      - key: EUREKA_CLIENT_REGISTERWITHEUREKA
        value: "false"
      - key: EUREKA_CLIENT_FETCHREGISTRY
        value: "false"
      - key: SERVER_PORT
        value: "8080"
      - key: JAVA_OPTS
        value: -Xmx384m -Xms128m

  - type: web
    name: ms-gateway
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_APPLICATION_NAME
        value: ms-gateway
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: https://repo-eureka-server.onrender.com/eureka/
      - key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
        value: "true"
      - key: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED
        value: "false"
      - key: SERVER_PORT
        value: "8080"
      - key: JAVA_OPTS
        value: -Xmx384m -Xms128m

  - type: web
    name: ms-ajuste
    runtime: docker
    plan: free
    envVars:
      - fromGroup: oracle-wallet-shared
      - key: SPRING_APPLICATION_NAME
        value: ms-ajuste
      - key: SPRING_DATASOURCE_USERNAME
        value: SCHEMA_AJUSTES

  - type: web
    name: ms-bodega
    runtime: docker
    plan: free
    envVars:
      - fromGroup: oracle-wallet-shared
      - key: SPRING_APPLICATION_NAME
        value: ms-bodega
      - key: SPRING_DATASOURCE_USERNAME
        value: SCHEMA_BODEGA

  - type: web
    name: ms-categorias
    runtime: docker
    plan: free
    envVars:
      - fromGroup: oracle-wallet-shared
      - key: SPRING_APPLICATION_NAME
        value: ms-categorias
      - key: SPRING_DATASOURCE_USERNAME
        value: SCHEMA_CATEGORIAS

  - type: web
    name: ms-egresos
    runtime: docker
    plan: free
    envVars:
      - fromGroup: oracle-wallet-shared
      - key: SPRING_APPLICATION_NAME
        value: ms-egresos
      - key: SPRING_DATASOURCE_USERNAME
        value: SCHEMA_EGRESOS

  - type: web
    name: ms-ingresos
    runtime: docker
    plan: free
    envVars:
      - fromGroup: oracle-wallet-shared
      - key: SPRING_APPLICATION_NAME
        value: ms-ingresos
      - key: SPRING_DATASOURCE_USERNAME
        value: SCHEMA_INGRESOS

  - type: web
    name: ms-kardex
    runtime: docker
    plan: free
    envVars:
      - fromGroup: oracle-wallet-shared
      - key: SPRING_APPLICATION_NAME
        value: ms-kardex
      - key: SPRING_DATASOURCE_USERNAME
        value: SCHEMA_KARDEX

  - type: web
    name: ms-producto
    runtime: docker
    plan: free
    envVars:
      - fromGroup: oracle-wallet-shared
      - key: SPRING_APPLICATION_NAME
        value: ms-producto
      - key: SPRING_DATASOURCE_USERNAME
        value: SCHEMA_PRODUCTO

  - type: web
    name: ms-proveedores
    runtime: docker
    plan: free
    envVars:
      - fromGroup: oracle-wallet-shared
      - key: SPRING_APPLICATION_NAME
        value: ms-proveedores
      - key: SPRING_DATASOURCE_USERNAME
        value: SCHEMA_PROVEEDORES

  - type: web
    name: ms-traslados
    runtime: docker
    plan: free
    envVars:
      - fromGroup: oracle-wallet-shared
      - key: SPRING_APPLICATION_NAME
        value: ms-traslados
      - key: SPRING_DATASOURCE_USERNAME
        value: SCHEMA_TRASLADOS

  - type: web
    name: ms-usuarios
    runtime: docker
    plan: free
    envVars:
      - fromGroup: oracle-wallet-shared
      - key: SPRING_APPLICATION_NAME
        value: ms-usuarios
      - key: SPRING_DATASOURCE_USERNAME
        value: SCHEMA_USUARIOS

envVarGroups:
  - name: oracle-wallet-shared
    envVars:
      # !! Asegúrate de que esta URL coincida con la de tu Eureka activo:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: https://repo-eureka-server.onrender.com/eureka/
      - key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
        value: "true"
      - key: SERVER_PORT
        value: "8080"
      - key: TNS_ADMIN
        value: /etc/secrets
      - key: SPRING_DATASOURCE_URL
        value: jdbc:oracle:thin:@mmg8hvewk688yrh4_low?TNS_ADMIN=/etc/secrets
      - key: SPRING_DATASOURCE_PASSWORD
        value: FullStack-Bodega1
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE
        value: "2"
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: none
      - key: SPRING_JPA_SHOW_SQL
        value: "false"
      - key: JAVA_OPTS
        value: -Xmx384m -Xms128m
    secretFiles:
      - key: cwallet.sso
        contents: ofhONgAAAAYAAAAhBl8WNyjkwSby0ZTzNWdrC2HTqRVH4lQNCcDF+Aqn5BlcMIIc7AIBAzCCHLIGCSqGSIb3DQEHAaCCHKMEghyfMIIcmzCCHJcGCSqGSIb3DQEHBqCCHIgwghyEAgEAMIIcfQYJKoZIhvcNAQcBMCQGCiqGSIb3DQEMAQMwFgQQDUjPMDqNq/tbbPWZnTWVdgICJxCAghxI5qSEX4Do3F3zgbOWggad0frwwpwwSbik+lgrg5t2nIz9PtuCjppeNR+gQuZoD0I/+Wy/MtrRPypI8Ab9TILFMs1v1RMUw2uBxLUF+kyVL8M14JgC5ubGmR4hEnDFA7qmduBxeXKGnGY4nZWU8j9riTeSdOZdV4tw70PUGJdsB4KuHQj7VCcAK9rnN2D0U7IreBGuI2PaycjTWlXwnz8nMFUJm3NTJj8qdpf0b7GnxwUWlRY1kbuVL2+iQC2MYgPqiMoqvv0tj8NhOKS7r71FUY+qkRdQ9d6OVYv3grnwJMCcCzaa37fzS0msu8n1YK5CYYWviF6x4ZE0Ezl6RzQ3Kpo3TvnXq+tnDtEnsoOH3AtMmX+iy1Bn1jMA0+V3m+LznscmUduz7OS7rNUA9gt7fiE62OiaKua0oG+ElxAgLk5jifAhJVPBE1PusWx3uNTCKB2rU/xRfZ5FMUM++7+8R6XWQQWPHg7MvX/TeW3u/CyQtO5S06DNvz25zMz6v65rRv+gtZBlHrzVTBEF9lQrccWeCDKG8BWDAbSNV8nq6QykdjKpScrZxmgKfWDOfZ/xlCrZsAbhxMgzARmkB/41a8x3O+irPrZnohDDEGS/MEBFz7YD+ohl0QprEzWMPT/B/XJLP+FMmsCZAUvPtjs2MvyajWeJyP056ViuHQCNAV/7ypDSBFPCQQmnyjmHk4GbWFlbFZOjVLA6bv4odW3EKBpchl7KxxSA9LHX8uJgCmFYcVYPvXap0fsNvBiAqG8Au3cE5JULHjQ1dtSyfsB01GC0JmlaHiGz1XCuYkAABa1KM91f39pWqHWCQ/8RyLbzLw7nuKFxURThTfZu4VXkqcGmoRmP3od4CDjn8K6Nhm/LJMx/8a6eRiqKn91Xu0zARtnqpIudGz8nVs4kQrJuZ/fku4y0/eEG9un9TvEFO/xM1kCafDMKnM09COQh+sDJHF4A5DvP/iXbBFr5FKTnHCzhVQlYMVrd9kWs2sMiz43ljGzP2skKdn1G1Wb6InxkujKO6n94Os0Od6Dnl6n93+mMxA17ren2fH16WnPOacVKpKeC0yr5BTVTokbVlglo4YO6xoknZyvaq9rOkMjgWfUPHB4xuncn2b6+3YDMTrl/e1uUG1UWAGw/u5r6PRD8Dv6NM/UsRzhhfMvXjTBu+KSjfENmMGBG8PLJ7PP6+fZ1+LXc/yWWbCjyEZamM5GSpv4+00cKZCpXIqNXtmq3twozlMdQr3mM8sp+WCGl+UQrpuT0VgW5erFSQcDVNCU+C9hRKA7+wxvkKTL8thtjpmwnNgfVB2QxlYCiSYjTW7yih7fiqXahTCd7QO6Z0e9c6c6aEOcdWzf5EYrujeIfl9oW8YkZE7ebs+VZlerBsOq6l+Gxa+yHlyI5xNymfMeyXr3oHYs0+EiAkU3qyXkjcOQZzhgkjP3P5bqv8r1OXswikF5b7WE9dIvLdDfBViYdhat6VTeKEINwx1kcF0VWHu7d79t8lGPMVKV/qynG/aIm9PpQ8ft1UI7q4omUzvtGnGZixbImY1weHx0fC4NNBT4zOfbGE7PafVt3uJOefJWNbiHk7fE4ctvzxmD0rTDCeeDepef8v1QVrJH9u+fk6G3yKSUXclqciF5mggoY+i/edO0+YlCNZWnqs+NJFWJlVImnN8LQBUjr2QqfPx+JCg4WF0pTW2XYxt0ox2kdo6spuc6q9IlutcezEywtz8+mgM2EuB2l4ECIXhIo5wSpn3qJFih0v0SDHwX5Wa0rTuRTwE7Kb7d8ThanQO0nDJCoflzPUX2RcXFCsQR2KXV4v3Kcwd/Giip2K79W6VH9QqSixcpImR13iQYYSeo7rNQgtJlOdkx1/ndQJqr5vCbH4wBeliEdn7ea36BUcXaFXVlPQz8jGTGdDpKqhUo31CmjYW9MzJXyCo9XjJuksYqDwFMv3goN0Hky/B8FgGcS1gv6cqMLWRyOpgcATRrtUIsqpTAp4z89fhxDH599nuOFW9R5/wtLV5d+FvQsXLRImtWGI0y09h7XZT+bL7eXlCmRcyTeI5v/VJLJZVaY5Oi/iHto/qbDi8bzgB74OLyJ5ZfO4/WKztxIsyCXE2eNLSE5wROfpH5BR3G4cIV0wtXlJNZK1/tg/bilne88Vc+2VVCG4HI2oTjcYCovEWeL/5dG8HM6Pqsc8RttRmS+lfpLH8qf5ydhCV0NST+QbcptE9FsPRYJu6yb+NL0/uZ7lU8cBzJ7Vtgpvl0sUOb96zF2P4IFdmySQTUt3rv4NsCp4WojrveR6A4CPgEUJDTteAV32oDvEb5lzqa4dBKlz2ewJt1IRZsSnGXnzIFjbFbpHzRC6PFYZppaQ1Yybscw78X9jWqFOt+se7CLBmCOeFrOR8knnQ+d+Cso3cWvnn7gHZ/LfAtmwqIn+Dz84HvELQ39t8ZbWVMt6JX4dwDv772PmqusWgaSIp5a0kKiMIXAm7yBs5HUi1f+yP2ROk5YHOAPjeKmS36CNGt3TaUVNNQWTwUIDEIQsTkQljqyGm8SPbGEAkLJB/U8ncIKEjQl8Skk6hWcbZO+QtxFaAFDo+b72m8toKa3IUrHjjGP2DfGnq5Q6gMyrq1HckFifUHx8NbQSO3m4Lt7YFRZ8d1w4hQc1EQwv/dS1/dd1FjswA1FALY7UQAmZyglgT2H8bgm8BJ65l/LtcjySkk1yLvymPYSKOE6AmCrhN6Ppbq0VCSeWt92HcyP4A/UaC5kU66lexVuSV6Aj9cgZMAvfLzqHNs2UVFcj4a0PuCg4Sk7Uu2XDaxUdFDDuImNW4Xk/rIjcd9RDYsqJkbNtVpLpw+X2ovNlfFIRv/gMs7EsBSzpxH6ApEtOwEE59Xle33FS1g20rSHtHmUYkUbg2Rme+EJ+GbJvt+1BnmBCDhvOOhHzRmUoueJCU5pUXpUdudmSNLU97ZeddjH3w2RKUKA/3Q7zSwxkTYEvikXpSl9ByB4H302zxDmAfRPfRNIfKunG+t3mvp8TyeN5QTyXFInhOtLn7BhvhVm+xhKwWGd7iPWJ+2zb8UhaJVo0lIyDDPzNKD2k+LSNMt+q8ePtAv2CTGVIhAnwaIIyScLgIQqu0NxoSioq7gN2cXYG3kVeFjnhmHGAzNIrEccquVsuihz5tW3PjAp9tMpZfoP4A6+jVjMkDgqAXPt8Mo1E1A3HPGuhMEZwkPJ/QByjLuiPoihech2Q2l7XFByaF1FlmvmYHsFRSuYvx14PL9Jtw5TMkhB0EGNajGhMNlC3ENCd3TlaeM9ZOJer6NvIZKoTNHUJDxqeocidsKOQDM73/ZXwXKUuuVgvd8Xa1+auWi1/pPliqkZMIt9PTsDVTwvtvRO2oWUcdQxzB03guqQf6sMsxLyWUvoV6CRzAOBOyssa4hWhhvyGCjtL9NOvjOpeLzqY9NjFqi5wvXTlX3oaMkUw7aZdOtjUBETn8Vt/wBNHK79Gh/v8nA9D/l8uSTY9o2qPHQIJo4xVFc41A+mHhXr3kcKUq0uGUsC2odgtfEVHGuo55msd0SE5zT9560X/308JH4zJSDgl++FzrOW/UMgMmvfH+uxIi1+GLzHc8qJJBko7K9UzN8+awVReAanoLAWyS0HN888fiBwIN2KOcokxYV3snEFFSDcQTo0ijMxvAUqJSXP6YDY7FjBYXIgIcunOReZURl++2wFgfkbCMaywWy+QKrRiwsp0PjfjJv5J8Uan0Tcib31rTjffiRT6EkXyb3PXzBW8xoP/FJsBuqxZTgF4+DJLc7r2fYLsUpCfki4BRDd7e7fTX7lDo4fhMMixAHgsoHfiA4Vo4hKjptY91qspUUj7ny5eDKHLzG13s1h8G0PxLquAEDJMb7M52ThSgvwUwr/d21m/AsNOMVvY0jmNvCM30b0cms/rMACdDECCN3pX2srjAkyEgU/rTK3YdHRtR0JkBbrPMfwZ40x9zubcXji/wg1ZNPhIOIcbbtYVQdeqvsR4ghI9fcqrzkacFxWf1SwsCCzLg1LKiJMcYLFAQPoamd+frm3EroPGhCRRSHG3bKIa2CafQFe0abKfefyH7O+6YLdpXByU+iS/gcV8JxAQaDvglnlS1xHfDER1jI/VQ/ELp1N3VGcGuV901LMrvke+1uiFkiyZ6JyOoDhJDjqjv/IU3WDdyIwHQeqyINfP0p4eWXDAhqllEf2XFMZ2356vu2Oy9cWFvVzkwGLJQNA8htjz9VPlyr4A2WP/upN120VyJ9ZQc6Ml8AfhO+GdiGWGXEarKwP2Y2XN027VPrY5EQEJ9uiDq1R/efXPWn4vo6JZkW9KSCuzc1EiTRonjslrewUIm5VgufP8IEX05d43P2CImIbjBj5oxwwJQFArvjq0pMuIURbGpuA3AD8LKVZ37sSmKgE44tJedGP/2i5aByfw6YQGN8tQnW6lL2VckZF+5/9seA47PvAO3l7X1ZHwDBLG5NtwxeCF9VIU3ONhM38UxdDVgC7aGH06dXT63eb/uApBzs+CgIWvB2U6awSsDcg4RFbjiPwPSEMAU92LWgfx32u1J94D2GME7Xerj82oVE2SFZk0RZJxTb1/DMlULy5+uXvS4J3S8Tv4rmQgIRcY4LqnqRfpwyZg4fmuWNSL+XnaHlr0w9nXTqBjnTIiSPIVRk1ZEqZS5vjl0Y3g2rUWBpb/nGj2DW2Wzh992ZBxvcvC6io7PlOiTKQJjfCNKxVnPDVUuvHyudA9qr1lUW1sMmfQ0EVj+j3/eBcPw2SeNcfw5EhCfbQBHGtWvc8If/58YOuwfj4xqgszyVMekN5stgUVNnT4f319YVPrxb22Ik6pT6+rxKVI8Y1CLjZpWFl/Gd/R/2k/ZkSOGp6/mDCdeid0Tfm5zdlllVeceWs6UC8T2rja8dkXRp7GALGruniygs4T9c899zoWhJ8nvDdoBL9k2dAdjioZl8fuZ5sA0r13oZFQWvh8QO60KAT8s5IK+2o5lbAuKotwwDQ3j8btTYzyHWrRODHH1uoYXu7yyvVXVYi1Jv9x/Bk0CSFX7ktwZpTSxlars7gk2pU/Q0c+xe5nDyGdtxl+juhA+NnMuCgEl6ybjxCSsZTIo443mLh41q+8vxM6bDzh5BWE4SbMK1k12B4UJoZXklL0T/7CqUAQjJYrdIrCUKfoBWoj9mTmF/ku8J1zNbwFspXk/7mUdJSF60/WCeqa9+fcrWjPXVUHT7jBIgqGD6qsRawtBSSqs+Qus4dW5QAd4cc0fJ1ckPDFUY9gB0bBi23ITKcujhQVPTTqlMJKSBMa+xXNrlJzq7nmwM7hQixXPfZxmLVhtcILvHqQE9sk5AMuOEkCu9Ij8lSdEnkJlX6oqbQA7RIOU21E5nKLHazX3M7g1Wrb2ku1ZV1ArL97F7pZMXx1g8NdRDxwiLDfLtgtVfs9HcZSC0mIJtc26/1WJzcBn2CxkBIQE2L51i2G2D2wDoDimiNxw68i0IA6UXeCw+zj16lXYca86E82DnEE3Qe8HIHbk4Vk5dxZ6c7XpkRvktX20ncpM/cFGn8zv5txYGFw+Z76ld/hKNaAayDGLXC0whjTf+D8hLKSc/exOup0e4uddCHZCn+FZyAdS9mGuYGG8NUZmY4I7xIZrwmw/8s2C3VbIuJEiSbFF0nLf4U9hyGbXs3o/s2g90/2sFoBN6Xy4kFjOWTCL/4tMPvp0r6YRCKwIk2mkDGGPO4HQRmoUCl9MSTymGKrSUvfwwxA8skvfQG39PQcdmB+Wn3rWnsRg3fW7cl7OIWwG45yKjQ63robuQ31K664GIwhzg6SS3X0ji3YJEGLWxxapIXya59llRCHWhcWyKGVl5MejGhcODuZOeFTTbehDRvdk2+LXDe3Q3wQnrypXJuicOWs/vOtYRGdukzh5oZXIujDy7+YChexYy/ZnlCXGEkihm6dYKqFWZAJYP1N9ZnvE3ceE8PgdE+ad4NrelukqmnP0FC+zOk324rPlD1kupNSGmw1UFI4T5f6/90KM1c+or9xz4qcTokM5eH7anBM/2xGLYSBAJv9i3WiAeClKyAIFcarZOzSx90gyPdX6G3w/p/0lDYOt70Q+uwDbtQzgpxqvMilxQuw0BDvEJ2c94bxaLTFt+V7B7YribFL80DFW2TRBJCppmyCk9CqEnuKT9leaLW8ZSHPRR0cjIo3iGp/7nfREwc95zt/psaOShcNeTTdWlgRfc20/YDvxwpvXffrh6dk0vPY3jiBCKLTKqNTKCc8KogQHx/rsg6TaGlhrjqYWjIjEMEPZHolyakeVTtqcCX+H5j6PqLca6IN/JtktOfG5gJeJ+tmjb+VrpIzdSxPaRh3jIQ/5sptvTIfQdbr3eYPItObiWxY/5/sbrGZSaks7I4h0Bwwar9vsqQiA2Pksw2Ka9RcdiI72f7PH/fT3lGh4s5meSCwA4D8mR2efvp4GcF3ILXprlsc+wq5hZZawhH5iIlp9Jwv0AamyODZ5Bmol+O18R7jwZk11n1FM7Crq3RrwOVFML0z7wRCulxxy0ZG37y9ilqKsSVWG5W3+iKbxvT8LFSmZz49nVbtABC12HNZtAeXw0s0q+n0UZSiM8/qYJdnTb68MxD8yYlY1oex4TRtpIU8i34854m2Ge1XA+KBXNqbr51J/EddrSrHFqCppRXrdNNs5+Vp04uwFqf8qSkj9T7M81meraRSyyOV8/aITqG7LBrln1939yrI1yRk1KQyZCvZomHExroabww6H03se8wKYvTrLcpRpmanZdVrDMsXEAsOKc4sRuiBrqIBD8eRtItElSvCbhAOY2MfuwCfvGdstji4PESh8KpEEry+nvrzRVBEFJmCEb92ozwtukT9C/dNnpTjN8N+/dXc20Fa0PUqFq8wNzR0EMMxLtMOSKY9fBNNfnfQQusdntdlYdanTRnXyTJefH2QVhNV6BsLHjRbabs8UdpA30syUpvYtcvzDkTyFwi/VLy0rDXeuz+S95dqn9KAY4S6zGdfdVMqn7oFEni6fMYp2xyqVKTFinwecsOLmkGFj3uWhKy7QMtdBQbZE7hqi8zoXWm48P1oEBk+pUiS77JIcCaI9dQ4ocxKYS47leWr1DBDtSzkVfuHotwcAR4OyULflqxYsVaKlpDkpF1DgJQpP3+5k3HZvzVuucPNi3RUlnFVvvp2Hw6JIPDhkA6azo0ASoeuedZBbxRLzdbeg9g5ISOag37ViCIC0t2ihqP1/C7qNdXxxWJj9sO4qeKxx32DrjbvRH7UIIDF/P5p8KRTQIbYzi3JEi48bn0JDnTqYYfUKiy7TTpkVhwIHW7jquyIArtFqLoB72NiOQc0BCullJaUV6b9MOOsU+qAIVAbI0MSn3AtP5BuwhE+zFzm0v4hB+kLrSRZPlHTvmnupnmJ/sibNtkmStQnq6pjL3X9OTRYSZ154uCRqm2Y2huhVRVLCZ952Qyj0B/FgMUrEsf8CUpc7UQ66GpXKFw2C6faQfA9RIIB50EfMgnfV1Nuyq4LThMfYbl7bqb8FXMN38tlQlw9tVguuu/hd11XxaVkzzJNptNp9lfDbyYzdez8lO2n87VYdwBNuhTe/iGXkvdiBTNTLTRw71dxxcHVfoen+yYgbIU3kTxN+LCAaTvlL3TjGFBsJVrJUgTUM8Xn47msDiBLU4zrD8kACc6N2w+wydSNGjLbF/COfLqn6lBgBqO/Zg/NitKA2VxH4RtOd/lRGDtbrQi/g8LrmQJGIUgcEcJ2bZlAf3E8QBzInhQRlKGMdgoaR0GEBkxK5kYNeOuyEJRQSWzVK7Ob3hw1I+wi7AssA3ZfVMRdXWSVnBKlfheXsXYW+V7Xn6bGePYwT6MkZAJNNmINSBeOseXt2fmj4PwQXFtOj4JP0ZCd4xVuNZkzacPcsdNR28eCh8xfQ8mqCFBwgkXprKE7ni9Ayv8G36Mt9mUH2e+9P0DDXNnqUTNv2DWUr+3qVtlBEl3Schf0xZZytgoqDfETJ+fmUs1lsug0+gq6Bz7jkmBJ18n4Xdk41h/Tif4wVSAXk2mg38Cd9JTr9j8KTO6uEknLGXQu9vWfvsNDaW3lgSPv1G0iciTsn95MtV9yO+TGXw5Dbe9Qz/HSDvE9QXqxCCZuGfZOvgiW0/KWD1R7gDWuVEz0jzwqlpTyTGLDfeyLuPc7/5UOMTR0f4ocAPprQy8Ac7nwvw82QpTOuZV3aosPm5CaceWAUMDvS5u9RaPC5slo4JbyK5SjqUQedgJboee0HvobVTBBZpoZrdL/blG/u34Zg9Iaf6bMXP+I9DyfjC82xosweD3qIR8Kq0TIrsBT8O85V8sBpqEOgFJq/Gccb6Jq7aaNj0fPFuYqqxyJOC4R1wKc7BVcdzH+HvaNdWdsqqCp/6i2JhdNEiMCu+3mO5nei0ePAC2Tin/sGKZHQc0tLBSXEKzechjTfWSyfR11kMG/E0n0qpcPQ/zHroopFJDKt8A3BUmC0/ZXYNwjlah81m3VdmCB3NuK2CcewXDuqfBMfU64akdGCFo9KcVUhip74bOArdTczj+CKgU6FrbaQXJ+jjjmNMK8S2URrbHaVw5c3R2Knl2KfV/aUhdaDDfGNmSQgdgC9kSSUqvewrMASZ6+wstyfvSlQqDN1Oo43YtuHR/xkvQ3usjdepNfXFCcKsH3JTVRFe3Udx0l9IESCknFsGCuFaSWhR70LlJlVjFYu4ta8Y2TVRPAlHiykZVAlYqaHGrfgWRvVB1ypXEsxeeW/WMAhIeQesUj26/Hn92ypUOe+FAPevvVPSXRGrwVBcJkcJRNrl6t9P2KcShTB/cJH10u5DgTsUFwIb8ZU3i5/5gxr3sIlAgYarkP8V9baNmV6YVMBBb48WCt7Tk7o33HUgu17k4R33ZGHJmnQfDdlQkUS2nXZK5crQvT1IOR6C4hq9N78P6TqwgmYwRlzmJWEQxpceeSuw6I9RKNcej6sI87ogIo4URW0+tOBwyhV6s9ZZhgYnuPpBcPTeIdtwHo4sXmtuF733APjy0Qy0eoSwEAo95m3lHencj52kdrx5FriU7fi7QIk77FqCmOuSxVTVSJTlWqp4Uxr1qK427rrk8Qi8UVsMCZSlHrJ87zOdEBVpZAL8R0GCGaG/+kFa0eIwFYHeAWT2RYSlvoENVIhcjBJTepjRjluR2PwRCz9aNiQMrTaOPqhemNhQJMUw4Y5T9mU6Vd8cy5g0QNTNMHnd5O/bbsLXstYpmDfQOsDqhqlWXauQUglnFSr9VNFDK0JpkhjTwMTHwfI8KxuxrKjp7Xjev7FbEmAPL0cBcreuUAviSleESZIoH9Ga+hZNBD4Cph5S5jq3IevMd6YriTxfWLCgQJMeDaFHxmsub3yDvyLk9u3wvc5An19BvkQsv2gCiYoozF0bgG2Ze5m5qnKSJA0CZFkJG8+lK6erqw0qf62NaNeosQ9WlqABLd15JP+giHIVjXjFLg4BsomW+rJ59NkU97BCnNxq+gUXrfh1tP7JizyoJjosS3dXRqwzRtsQu4jiU7fpv0aC2JnwczSKGTyFk6x5Sq1QJV3Pr8/ueJEWkVgbpL/dsDmUu96ULK3SNCeITGDWmST8pkAPgpAgijE2rohQtyFeoM494ZDIbLZRqWZCgRpqGbmCPPwRnrRsyDlxsKRT64KiN3PxfHTAxMCEwCQYFKw4DAhoFAAQUrzjN78vZ5+K2rS+0jE9s30wFdpcECFAnA18n51XDAgInEA==
      - key: tnsnames.ora
        contents: |
          mmg8hvewk688yrh4_high = (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=g0fbf24ba59b790_mmg8hvewk688yrh4_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
          mmg8hvewk688yrh4_medium = (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=g0fbf24ba59b790_mmg8hvewk688yrh4_medium.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
          mmg8hvewk688yrh4_low = (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=g0fbf24ba59b790_mmg8hvewk688yrh4_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
          mmg8hvewk688yrh4_tp = (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=g0fbf24ba59b790_mmg8hvewk688yrh4_tp.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
          mmg8hvewk688yrh4_tpurgent = (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=g0fbf24ba59b790_mmg8hvewk688yrh4_tpurgent.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
      - key: sqlnet.ora
        contents: |
          WALLET_LOCATION = (SOURCE = (METHOD = FILE) (METHOD_DATA = (DIRECTORY = "/etc/secrets")))
          SSL_SERVER_DN_MATCH = YES