server:
  port: 8086

spring:
  application:
    name: ms-kardex
  datasource:
    url: jdbc:oracle:thin:@mmg8hvewk688yrh4_low?TNS_ADMIN=${TNS_ADMIN:/wallet}
    username: SCHEMA_KARDEX
    password: FullStack-Bodega1
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # 🔽 Configuración corregida y unificada para evitar el error en rojo del editor
  web:
    resources:
      add-mappings: false
  mvc:
    "[throw-exception-if-no-handler-found]": true

# URLs para el consumo de API interno
producto:
  service:
    url: ${PRODUCTO_SERVICE_URL:http://ms-productos:8082/api/productos}
ubicacion:
  service:
    url: ${UBICACION_SERVICE_URL:http://ms-bodega:8085/api/ubicaciones}

# Configuración de documentación con Swagger / OpenApi
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Integración con el Servidor de Descubrimiento Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}