server.port=8089
spring.application.name=ms-proveedores

spring.datasource.url=jdbc:oracle:thin:@mmg8hvewk688yrh4_low?TNS_ADMIN=${TNS_ADMIN:/wallet}
spring.datasource.username=SCHEMA_PROVEEDORES
spring.datasource.password=FullStack-Bodega1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka-server:8761/eureka/}

