server:
  port: 8080

spring:
  application:
    name: ms-gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          # Permite que busque servicios registrados en Eureka
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-kardex
          uri: lb://MS-KARDEX # Usa balanceo de carga dinámico vía Eureka
          predicates:
            - Path=/api/kardex,/api/kardex/**

        - id: ms-categorias
          uri: lb://MS-CATEGORIAS
          predicates:
            - Path=/api/categorias,/api/categorias/**

        - id: ms-producto
          uri: lb://MS-PRODUCTO
          predicates:
            - Path=/api/productos,/api/productos/**

        - id: ms-bodega
          uri: lb://MS-BODEGA
          predicates:
            - Path=/api/ubicaciones,/api/ubicaciones/**

        - id: ms-ingresos
          uri: lb://MS-INGRESOS
          predicates:
            - Path=/api/ingresos,/api/ingresos/**

        - id: ms-egresos
          uri: lb://MS-EGRESOS
          predicates:
            - Path=/api/egresos,/api/egresos/**

        - id: ms-ajuste
          uri: lb://MS-AJUSTE
          predicates:
            - Path=/api/ajustes,/api/ajustes/**

        - id: ms-traslados
          uri: lb://MS-TRASLADOS
          predicates:
            - Path=/api/traslados,/api/traslados/**

        - id: ms-usuarios
          uri: lb://MS-USUARIOS
          predicates:
            - Path=/api/usuarios,/api/usuarios/**

        - id: ms-proveedores
          uri: lb://MS-PROVEEDORES
          predicates:
            - Path=/api/proveedores,/api/proveedores/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}

management:
  endpoints:
    web:
      exposure:
        include: "*"